name: TaskExecutor service publish
on:
  push:

jobs:
  docker_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            path: TaskExecutor/

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: list
        run: ls

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: femex/app:latest

