name: TaskExecutor service publish
on:
  push:

env:
  image_name: task

jobs:
  docker_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Reformat Branch name
        uses: mad9000/actions-find-and-replace-string@2
        id: findandreplace
        with:
          source: ${{ github.ref_name }}
          find: '/'
          replace: '_'

      - uses: ASzc/change-string-case-action@v2
        id: lowercase
        with:
          string: ${{ steps.findandreplace.outputs.value }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./TaskExecutor
          push: true
          tags: femex/${{ steps.lowercase.outputs.lowercase }}":latest

